services:
    roarscore-service:
        build:
          context: .
          dockerfile: ./Dockerfile
        container_name: roarscore-service
        hostname: roarscore-service
        volumes:
          - .:/usr/local/roarscore


